include ../Makefile.defs

TESTNAME        = simple_matrix_dyn_array
TESTSRC_MAIN    = simple_matrix_dyn_array.cpp
TESTSRC_AUX     =
TESTSRC_ALL     = $(TESTSRC_MAIN) $(TESTSRC_AUX)

CLANG           = clang++
OMP_BIN         = $(HCC2)/bin/$(CLANG)
CC              = $(OMP_BIN) $(VERBOSE)
EXTRA_CFLAGS    =
EXTRA_OMP_FLAGS =

include ../Makefile.rules
